### ISSUE TITLE
Error after one epoch of training is completed

### ISSUE THREAD

**Issue by iazdan** [microsoft/table-transformer#38]
I trained the model for the strcuture task on the pubtable dataset however I got the below error at the end of the first epoch. Any clues why this is happening? 

Epoch completed in  18:21:31.466229
Traceback (most recent call last):
  File "main.py", line 373, in <module>
    main()
  File "main.py", line 362, in main
    train(args, model, criterion, postprocessors, device)
  File "main.py", line 319, in train
    pubmed_stats, coco_evaluator = evaluate(model, criterion,
  File "/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context                                
    return func(*args, **kwargs)
  File "/table-transformer/src/../detr/engine.py", line 81, in evaluate                                                            
    coco_evaluator = CocoEvaluator(base_ds, iou_types)
  File "/table-transformer/src/../detr/datasets/coco_eval.py", line 31, in __init__                                                
    self.coco_eval[iou_type] = COCOeval(coco_gt, iouType=iou_type)
  File "/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 76, in __init__                                            
    self.params = Params(iouType=iouType) # parameters
  File "/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 527, in __init__                                           
    self.setDetParams()
  File "/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 507, in setDetParams                                       
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)                                                                       
  File "<__array_function__ internals>", line 5, in linspace
  File "/lib/python3.8/site-packages/numpy/core/function_base.py", line 120, in linspace                                       
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an intege

**Comment by bsmock** [comment]
Are you using the same package versions defined in environment.yml? For instance, I notice python 3.8 appears in your stacktrace, but environment.yml is using "python=3.6.10".
